<?php

namespace CarInsurance;

class Language {
    public array $lang;

    public function __construct( string $lang ) {
        switch( $lang ) {
            case 'en':
            default:
                $this->lang = $this->getEN();
            break;
        }
    }

    private function getEN() : array {
        return [
            'api_code_100' => "Internal error.",
            'api_code_1000' => "Internal error: invalid language parameter.",
            'api_code_1001' => "Internal error: account is not found.",
            'api_code_1002' => "Internal error: account role is not found.",
            'api_code_1003' => "Internal error: account rating is not found.",
            'api_code_1004' => "Internal error: account rating is not created.",
            'api_code_1005' => "Internal error: account is not created or updated.",
            'api_code_1006' => "Internal error: create account DB transaction failed.",
            'api_code_1007' => "Internal error: category is not created or updated.",
            'api_code_1008' => "Internal error: category is not found.",
            'api_code_1009' => "Internal error: main product is not created or updated.",
            'api_code_1010' => "Internal error: sub product is not created or updated.",
            'api_code_1011' => "Internal error: main product is not found.",
            'api_code_1012' => "Internal error: vehicle is not created or updated.",
            'api_code_1013' => "Internal error: rating is not updated.",
            'api_code_1014' => "Internal error: estimation is not created.",
            'api_code_1015' => "Internal error: order is not created or updated.",
            'api_code_1016' => "Internal error: could not create account assets directory.",
            'api_code_1017' => "Internal error: could not create asset.",
            'api_code_1018' => "Internal error: invalid mail usage.",
            'api_code_1019' => "Internal error: could not create resource.",
            'api_code_1020' => "Internal error: bad logger parameters.",
            'api_code_1021' => "Internal error: could not send email, bad credentials.",
            'api_code_1022' => "Internal error: could not create accessory.",
            'api_code_1023' => "Internal error: could not create vehicle data entry.",
            'api_code_1024' => "Internal error: vehicle data entry is not created or updated.",
            'api_code_101' => "Login or password is empty.",
            'api_code_102' => "Login or password is incorrent.",
            'api_code_103' => "You don't have permissions to access to this section.",
            'api_code_104' => "Too many authorization attempts, try again later.",
            'api_code_105' => "Not yet implemented.",
            'api_code_106' => "Method is not allowed.",
            'api_code_107' => "Authentication credentials is not presented.",
            'api_code_108' => "Authentication credentials is invalid.",
            'api_code_109' => "Invalid request.",
            'api_code_1090' => "Input data is invalid.",
            'api_code_110' => "Entered password is incorrect.",
            'api_code_111' => "Too many validation code submission attempts, try again later.",
            'api_code_112' => "Invalid validation code, please try again.",
            'api_code_131' => "These accounts are not found.",
            'api_code_132' => "This account is banned.",
            'api_code_133' => "You have been banned.",
            'api_code_1310' => "Too short username (min length is 5 characters).",
            'api_code_1311' => "Too short password (min length is 8 characters).",
            'api_code_1312' => "Invalid email address.",
            'api_code_1313' => "This username is already exists.",
            'api_code_1314' => "This email address is already taken.",
            'api_code_1315' => "This client_id is already exists.",
            'api_code_1316' => "Invalid role.",
            'api_code_141' => "Categories are not found.",
            'api_code_1410' => "Too short category name (min length is 1 character).",
            'api_code_151' => "Main products are not found.",
            'api_code_1510' => "Specified category is not found.",
            'api_code_1511' => "Too short main product name (min length is 1 character).",
            'api_code_1512' => "Main products in specified category is not found.",
            'api_code_161' => "Sub products are not found.",
            'api_code_1610' => "Specified main product is not found.",
            'api_code_1611' => "Too short sub product name (min length is 1 character).",
            'api_code_171' => "Vehicles are not found.",
            'api_code_1710' => "Specified account is not found.",
            'api_code_1711' => "Vehicles are not found.",
            'api_code_1712' => "Too short vehicle details (min length is 1 character).",
            'api_code_1713' => "The field useCase cannot be empty and must be equal to one of these values: private, business, private and business",
            'api_code_1714' => "You are trying to edit not your own vehicle.",
            'api_code_181' => "Specified rating is not found.",
            'api_code_1810' => "Accounts are not found.",
            'api_code_1811' => "Rating is not found.",
            'api_code_1812' => "Specified account has no rating.",
            'api_code_1813' => "Specified account is not found.",
            'api_code_191' => "Estimations are not found.",
            'api_code_1910' => "Specified account is not found.",
            'api_code_1911' => "Specified main product is not found.",
            'api_code_1912' => "One of the selected sub products is not found.",
            'api_code_1913' => "Account is not found.",
            'api_code_1914' => "Rating is not found.",
            'api_code_1915' => "Vehicle is not found.",
            'api_code_1916' => "Unfortunately insurance has not been approved.",
            'api_code_1917' => "Car value limit exceeded.",
            'api_code_1918' => "Estimation type should be \"estimation\" or \"accessory\".",
            'api_code_1919' => "One of the selected accessories is not found.",
            'api_code_201' => "Orders are not found.",
            'api_code_2010' => "Specified account is not found.",
            'api_code_2011' => "Invalid input data.",
            'api_code_2012' => "One of specified estimations is not found.",
            'api_code_2013' => "Invalid order status.",
            'api_code_2014' => "One of specified estimations already has been used for other order.",
            'api_code_211' => "Assets are not found.",
            'api_code_2110' => "Specified account is not found.",
            'api_code_2111' => "An array of files has not been passed.",
            'api_code_2112' => "Invalid file type specified.",
            'api_code_2113' => "An error occurred while uploading the files. (1)",
            'api_code_2114' => "Invalid file format.",
            'api_code_2115' => "An error occurred while uploading the files. (2)",
            'api_code_2116' => "Invalid act.",
            'api_code_2117' => "Invalid asset id.",
            'api_code_2118' => "File already uploaded.",
            'api_code_2119' => "Uploaded files limit is reached. Try again later.",
            'api_code_2120' => "Uploaded file is too large.",
            'api_code_2121' => "The field relatedTo must be empty or equal to one of these values: orders, vehicles, avatar, driverLicensePhoto",
            'api_code_2122' => "Specified order is not found.",
            'api_code_2123' => "Specified order is rejected.",
            'api_code_2124' => "Too many files have been sent.",
            'api_code_2125' => "An array of files must be passed, single file passed.",
            'api_code_2126' => "The field relatedTo equals to \"avatar\" but fileType has other value.",
            'api_code_2127' => "The field relatedTo equals to \"avatar\" but more than 1 file has been passed.",
            'api_code_2128' => "The field relatedTo equals to \"avatar\" therefore relationId should be equals to current accountId.",
            'api_code_2129' => "The field relatedTo equals to \"driverLicensePhoto\" but fileType has other value.",
            'api_code_2130' => "The field relatedTo equals to \"driverLicensePhoto\" but more than 1 file has been passed.",
            'api_code_2131' => "The field relatedTo equals to \"driverLicensePhoto\" therefore relationId should be equals to current accountId.",
            'api_code_2132' => "Accepted avatar resolutions: from 50x50 to 300x300 pixels.",
            'api_code_2133' => "Specified vehicle is not found.",
            'api_code_2134' => "The field relatedTo equals to \"vehicles\" but fileType has not equals \"photo\".",
            'api_code_2135' => "The field relatedTo equals to \"orders\" but fileType has not equals \"photo\" or \"document\".",
            'api_code_2210' => "Specified account is not found.",
            'api_code_2310' => "Resource key is not passed.",
            'api_code_2311' => "Resource value cannot be empty.",
            'api_code_2410' => "Specified vehicle is not found.",
            'api_code_2411' => "Specified accessory is not found.",
            'api_code_2412' => "Accessory name cannot be empty.",
            'api_code_2413' => "Accessory cost must be greater than 0.",
            'module_not_found' => 'Module is not found.',
        ];
    }
}